// <auto-generated />
using System;
using Frogmarks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frogmarks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserCode");

                    b.ToTable("DeviceFlowCodes");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Frogmarks.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AzureUserIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BlobStorageBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPro")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TeamProjectId")
                        .HasColumnType("bigint");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamProjectId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Frogmarks.Models.Auth.EmailToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTokens");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomThumbnail")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PermissionsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PreferencesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("SceneGraphData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartViewLeftBottom")
                        .HasColumnType("int");

                    b.Property<int>("StartViewLeftTop")
                        .HasColumnType("int");

                    b.Property<int>("StartViewRightBottom")
                        .HasColumnType("int");

                    b.Property<int>("StartViewRightTop")
                        .HasColumnType("int");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("isDraft")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("PermissionsId")
                        .IsUnique()
                        .HasFilter("[PermissionsId] IS NOT NULL");

                    b.HasIndex("PreferencesId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardCollaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("BoardsCollaborators");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<long>("OptionsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PositionDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("OptionsId");

                    b.HasIndex("TypeId");

                    b.ToTable("BoardItems");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItemOptions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BorderOpacity")
                        .HasColumnType("float");

                    b.Property<int?>("BorderThickness")
                        .HasColumnType("int");

                    b.Property<int?>("FontId")
                        .HasColumnType("int");

                    b.Property<int?>("FontSize")
                        .HasColumnType("int");

                    b.Property<int>("HorizontalAlignment")
                        .HasColumnType("int");

                    b.Property<int>("VerticalAlignment")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BoardItemOptions");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItemPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BoardItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Rotation")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardItemId")
                        .IsUnique();

                    b.ToTable("BoardItemPosition");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItemType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("HasBorderOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFillColor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFont")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFontSize")
                        .HasColumnType("bit");

                    b.Property<bool>("HasFontStyle")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHighlightColor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLink")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLock")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTextAlignment")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTextColor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoardItemType");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardPermissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<bool>("CanNonCollaboratorsEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanNonCollaboratorsView")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BoardPermissions");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BoardCollaboratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoardCollaboratorId");

                    b.ToTable("BoardRole");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardUserPreferences", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AlignObjects")
                        .HasColumnType("bit");

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FollowAllThreads")
                        .HasColumnType("bit");

                    b.Property<int>("PeripheralType")
                        .HasColumnType("int");

                    b.Property<bool>("ReduceMotion")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowCollaboratorCursors")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowCommentsOnBoard")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowObjectDimensions")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowScrollBars")
                        .HasColumnType("bit");

                    b.Property<bool>("SnapToGrid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BoardUserPreferences");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardViewLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastViewed")
                        .HasColumnType("datetime2");

                    b.Property<long>("TeamUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("BoardId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("BoardViewLogs");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.Illustration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AnimationEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("CanvasData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtendedStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fps")
                        .HasColumnType("int");

                    b.Property<int>("FrameCount")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustomThumbnail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("LoopMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnionSkinConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PermissionsId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayRangeEnd")
                        .HasColumnType("int");

                    b.Property<int>("PlayRangeStart")
                        .HasColumnType("int");

                    b.Property<long?>("PreferencesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishedBundleBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishedThumbnailBlobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublishedTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishedVersion")
                        .HasColumnType("int");

                    b.Property<long>("SavedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("SceneVersion")
                        .HasColumnType("int");

                    b.Property<int>("SyncMode")
                        .HasColumnType("int");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<bool>("isDraft")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("PermissionsId")
                        .IsUnique()
                        .HasFilter("[PermissionsId] IS NOT NULL");

                    b.HasIndex("PreferencesId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("Illustrations");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationCel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BlobSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("CelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CelType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Frame")
                        .HasColumnType("int");

                    b.Property<bool>("IsKey")
                        .HasColumnType("bit");

                    b.Property<long>("LayerDbId")
                        .HasColumnType("bigint");

                    b.Property<string>("PixelDataUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PixelHeight")
                        .HasColumnType("int");

                    b.Property<int?>("PixelWidth")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LayerDbId", "CelId")
                        .IsUnique();

                    b.ToTable("IllustrationCels");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationCollaborator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("IllustrationId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IllustrationId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("IllustrationCollaborators");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationLayer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Animated")
                        .HasColumnType("bit");

                    b.Property<string>("BlendMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("BlobSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("Clipped")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DitherConfigJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrameLinkAnimationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IllustrationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockTransparency")
                        .HasColumnType("bit");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Opacity")
                        .HasColumnType("float");

                    b.Property<string>("PixelDataUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PixelHeight")
                        .HasColumnType("int");

                    b.Property<int?>("PixelWidth")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IllustrationId", "LayerId")
                        .IsUnique();

                    b.ToTable("IllustrationLayers");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationPermissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanNonCollaboratorsEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanNonCollaboratorsView")
                        .HasColumnType("bit");

                    b.Property<long>("IllustrationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("IllustrationPermissions");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("IllustrationCollaboratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IllustrationCollaboratorId");

                    b.ToTable("IllustrationRole");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationUserPreferences", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IllustrationdId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("IllustrationUserPreferences");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationViewLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("IllustrationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastViewed")
                        .HasColumnType("datetime2");

                    b.Property<long>("TeamUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("IllustrationId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("IllustrationViewLogs");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedIp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedIp")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamPermissions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanAddMembers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanChangePermissions")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateBoards")
                        .HasColumnType("bit");

                    b.Property<bool>("CanCreateProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteBoards")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteMembers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDeleteProjects")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditBoards")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditProjects")
                        .HasColumnType("bit");

                    b.Property<long>("TeamRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamRoleId")
                        .IsUnique();

                    b.ToTable("TeamPermissions");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamProjects");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PermissionsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamUserId");

                    b.ToTable("TeamRole");
                });

            modelBuilder.Entity("Frogmarks.Models.TeamUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamUsers");
                });

            modelBuilder.Entity("Frogmarks.Models.ApplicationUser", b =>
                {
                    b.HasOne("Frogmarks.Models.Team.TeamProject", null)
                        .WithMany("Users")
                        .HasForeignKey("TeamProjectId");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.Board", b =>
                {
                    b.HasOne("Frogmarks.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Frogmarks.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("Frogmarks.Models.Board.BoardPermissions", "Permissions")
                        .WithOne("Board")
                        .HasForeignKey("Frogmarks.Models.Board.Board", "PermissionsId");

                    b.HasOne("Frogmarks.Models.Board.BoardUserPreferences", "Preferences")
                        .WithMany()
                        .HasForeignKey("PreferencesId");

                    b.HasOne("Frogmarks.Models.Team.TeamProject", "Project")
                        .WithMany("Boards")
                        .HasForeignKey("ProjectId");

                    b.HasOne("Frogmarks.Models.Team.Team", "Team")
                        .WithMany("Boards")
                        .HasForeignKey("TeamId");

                    b.HasOne("Frogmarks.Models.TeamUser", null)
                        .WithMany("FavoriteBoards")
                        .HasForeignKey("TeamUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Permissions");

                    b.Navigation("Preferences");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardCollaborator", b =>
                {
                    b.HasOne("Frogmarks.Models.Board.Board", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("BoardId");

                    b.HasOne("Frogmarks.Models.TeamUser", "TeamUser")
                        .WithMany()
                        .HasForeignKey("TeamUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamUser");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItem", b =>
                {
                    b.HasOne("Frogmarks.Models.Board.Board", null)
                        .WithMany("BoardItems")
                        .HasForeignKey("BoardId");

                    b.HasOne("Frogmarks.Models.Board.BoardItemOptions", "Options")
                        .WithMany()
                        .HasForeignKey("OptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.Board.BoardItemType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Options");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItemPosition", b =>
                {
                    b.HasOne("Frogmarks.Models.Board.BoardItem", "BoardItem")
                        .WithOne("PositionData")
                        .HasForeignKey("Frogmarks.Models.Board.BoardItemPosition", "BoardItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardItem");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardRole", b =>
                {
                    b.HasOne("Frogmarks.Models.Board.BoardCollaborator", null)
                        .WithMany("BoardRoles")
                        .HasForeignKey("BoardCollaboratorId");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardViewLog", b =>
                {
                    b.HasOne("Frogmarks.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.Board.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.TeamUser", "TeamUser")
                        .WithMany()
                        .HasForeignKey("TeamUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Board");

                    b.Navigation("TeamUser");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.Illustration", b =>
                {
                    b.HasOne("Frogmarks.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Frogmarks.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("Frogmarks.Models.Illustration.IllustrationPermissions", "Permissions")
                        .WithOne("Illustration")
                        .HasForeignKey("Frogmarks.Models.Illustration.Illustration", "PermissionsId");

                    b.HasOne("Frogmarks.Models.Illustration.IllustrationUserPreferences", "Preferences")
                        .WithMany()
                        .HasForeignKey("PreferencesId");

                    b.HasOne("Frogmarks.Models.Team.TeamProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("Frogmarks.Models.Team.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("Frogmarks.Models.TeamUser", null)
                        .WithMany("FavoriteIllustrations")
                        .HasForeignKey("TeamUserId");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Permissions");

                    b.Navigation("Preferences");

                    b.Navigation("Project");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationCel", b =>
                {
                    b.HasOne("Frogmarks.Models.Illustration.IllustrationLayer", "Layer")
                        .WithMany("Cels")
                        .HasForeignKey("LayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationCollaborator", b =>
                {
                    b.HasOne("Frogmarks.Models.Illustration.Illustration", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("IllustrationId");

                    b.HasOne("Frogmarks.Models.TeamUser", "TeamUser")
                        .WithMany()
                        .HasForeignKey("TeamUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamUser");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationLayer", b =>
                {
                    b.HasOne("Frogmarks.Models.Illustration.Illustration", "Illustration")
                        .WithMany("Layers")
                        .HasForeignKey("IllustrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Illustration");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationRole", b =>
                {
                    b.HasOne("Frogmarks.Models.Illustration.IllustrationCollaborator", null)
                        .WithMany("IllustrationRoles")
                        .HasForeignKey("IllustrationCollaboratorId");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationViewLog", b =>
                {
                    b.HasOne("Frogmarks.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.Illustration.Illustration", "Illustration")
                        .WithMany()
                        .HasForeignKey("IllustrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.TeamUser", "TeamUser")
                        .WithMany()
                        .HasForeignKey("TeamUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Illustration");

                    b.Navigation("TeamUser");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.Team", b =>
                {
                    b.HasOne("Frogmarks.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("Frogmarks.Models.ApplicationUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamPermissions", b =>
                {
                    b.HasOne("Frogmarks.Models.Team.TeamRole", "TeamRole")
                        .WithOne("Permissions")
                        .HasForeignKey("Frogmarks.Models.Team.TeamPermissions", "TeamRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamRole");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamProject", b =>
                {
                    b.HasOne("Frogmarks.Models.Team.Team", null)
                        .WithMany("TeamProjects")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamRole", b =>
                {
                    b.HasOne("Frogmarks.Models.Team.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.TeamUser", null)
                        .WithMany("TeamRoles")
                        .HasForeignKey("TeamUserId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Frogmarks.Models.TeamUser", b =>
                {
                    b.HasOne("Frogmarks.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("TeamUserScopes")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Frogmarks.Models.Team.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Frogmarks.Models.ApplicationUser", b =>
                {
                    b.Navigation("TeamUserScopes");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.Board", b =>
                {
                    b.Navigation("BoardItems");

                    b.Navigation("Collaborators");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardCollaborator", b =>
                {
                    b.Navigation("BoardRoles");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardItem", b =>
                {
                    b.Navigation("PositionData");
                });

            modelBuilder.Entity("Frogmarks.Models.Board.BoardPermissions", b =>
                {
                    b.Navigation("Board");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.Illustration", b =>
                {
                    b.Navigation("Collaborators");

                    b.Navigation("Layers");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationCollaborator", b =>
                {
                    b.Navigation("IllustrationRoles");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationLayer", b =>
                {
                    b.Navigation("Cels");
                });

            modelBuilder.Entity("Frogmarks.Models.Illustration.IllustrationPermissions", b =>
                {
                    b.Navigation("Illustration");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.Team", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("TeamProjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamProject", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Frogmarks.Models.Team.TeamRole", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Frogmarks.Models.TeamUser", b =>
                {
                    b.Navigation("FavoriteBoards");

                    b.Navigation("FavoriteIllustrations");

                    b.Navigation("TeamRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
